<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - Frank Website SEO Checker</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #334155;
						background-color: #f8fafc;
						margin: 0;
						padding: 40px 20px;
					}
					.container {
						max-width: 800px;
						margin: 0 auto;
						background: #ffffff;
						border: 1px solid #e2e8f0;
						border-radius: 16px;
						box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
						overflow: hidden;
					}
					.header {
						background: linear-gradient(135deg, #6366f1 0%, #a855f7 100%);
						padding: 30px;
						color: #ffffff;
					}
					.header h1 {
						margin: 0 0 10px 0;
						font-size: 24px;
						font-weight: 800;
						letter-spacing: -0.02em;
					}
					.header p {
						margin: 0;
						font-size: 14px;
						opacity: 0.9;
						line-height: 1.5;
					}
					.header a {
						color: #ffffff;
						text-decoration: underline;
					}
					.content {
						padding: 30px;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						text-align: left;
					}
					th {
						font-size: 12px;
						font-weight: 600;
						text-transform: uppercase;
						color: #64748b;
						border-bottom: 2px solid #e2e8f0;
						padding: 12px 10px;
					}
					td {
						font-size: 14px;
						border-bottom: 1px solid #f1f5f9;
						padding: 12px 10px;
						word-break: break-all;
					}
					tr:hover td {
						background-color: #f8fafc;
					}
					tr:last-child td {
						border-bottom: none;
					}
					.url-link {
						color: #6366f1;
						text-decoration: none;
						font-weight: 600;
					}
					.url-link:hover {
						text-decoration: underline;
					}
					.badge {
						display: inline-block;
						padding: 3px 8px;
						border-radius: 6px;
						font-weight: 700;
						font-size: 11px;
						background-color: #e2e8f0;
						color: #475569;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<div class="header">
						<h1>XML Sitemap Index</h1>
						<p>
							This XML Sitemap is generated by <strong>Frank Website SEO Checker And Audit</strong> to help search engines like Google discover your content. Learn more about sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.
						</p>
					</div>
					<div class="content">
						<xsl:if test="sitemap:sitemapindex">
							<p class="badge">Sitemap Index</p>
							<table>
								<thead>
									<tr>
										<th>Sitemap URL</th>
										<th>Last Modified</th>
									</tr>
								</thead>
								<tbody>
									<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
										<tr>
											<td>
												<a class="url-link" href="{sitemap:loc}">
													<xsl:value-of select="sitemap:loc"/>
												</a>
											</td>
											<td>
												<xsl:value-of select="sitemap:lastmod"/>
											</td>
										</tr>
									</xsl:for-each>
								</tbody>
							</table>
						</xsl:if>
						<xsl:if test="sitemap:urlset">
							<p class="badge">URL List</p>
							<table>
								<thead>
									<tr>
										<th>Location</th>
										<th>Last Modified</th>
										<th>Change Frequency</th>
										<th>Priority</th>
									</tr>
								</thead>
								<tbody>
									<xsl:for-each select="sitemap:urlset/sitemap:url">
										<tr>
											<td>
												<a class="url-link" href="{sitemap:loc}">
													<xsl:value-of select="sitemap:loc"/>
												</a>
											</td>
											<td>
												<xsl:value-of select="sitemap:lastmod"/>
											</td>
											<td>
												<xsl:value-of select="sitemap:changefreq"/>
											</td>
											<td>
												<xsl:value-of select="sitemap:priority"/>
											</td>
										</tr>
									</xsl:for-each>
								</tbody>
							</table>
						</xsl:if>
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
